image: docker:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - docker build -t frenetperformanceplanner .
    - docker run -d --name my-container frenetperformanceplanner
    - docker cp my-container:/app/dist/*.whl .
  artifacts:
    paths:
      - ./*.whl
