image: docker:latest

services:
  - docker:dind

build:
  stage: build
  script:
    - docker build -t frenetperformanceplanner .
    - docker run -d --name my-container frenetperformanceplanner
    - docker exec my-container bash -c 'for file in /app/dist/*.whl; do file=${file#/app/}; docker cp "my-container:$file" . ; done'
  artifacts:
    paths:
      - ./*.whl
