[project]
name = "frenetPlannerHelper"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.7,<3.13"
# license = {file = "LICENSE"}
#authors = [
#  {email = "todo"},
#  {name = "todo"}
#]
#description = "todo"

dependencies = [
    "numpy>=1.24.3"
]

[build-system]
requires = [
    "scikit-build-core~=0.4.7",
    "pybind11~=2.10.4",
    "setuptools_scm[toml]~=7.1.0"
    ]

build-backend = "scikit_build_core.build"

[tool.setuptools_scm]
write_to = "src/python/frenetPlannerHelper/_version.py"

[tool.scikit-build]
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"
sdist.include = ["src/python/frenetPlannerHelper/_version.py"]

wheel.packages = [ "src/python/frenetPlannerHelper" ]
build-dir = "build/{wheel_tag}"

[tool.scikit-build.cmake.define]
#CMAKE_C_COMPILER_LAUNCHER = "sccache"
#CMAKE_CXX_COMPILER_LAUNCHER = "sccache"
#CMAKE_C_COMPILER_LAUNCHER = "ccache"
#CMAKE_CXX_COMPILER_LAUNCHER = "ccache"

[tool.cibuildwheel]
# Skip PyPy and older CPython versions
skip = "pp* cp37-* cp38-*"
archs = ["auto"]
environment = { PIP_DISABLE_PIP_VERSION_CHECK="1" }
#build-verbosity = 1

# Skip tests on musllinux due to missing wheels
test-skip = "*i686 *-musllinux*"
test-extras = ["test"]
test-command = "python -m pytest {package}/tests/python"

[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]

# macOS 10.14 is required for full C++17 support
environment = {MACOSX_DEPLOYMENT_TARGET=10.14}
