name: Build wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: ["ubuntu-22.04", "windows-2022", "macos-12"]
        # TODO: Windows build needs a Fortran compiler
        os: ["ubuntu-22.04", "macos-12"]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_SKIP: "pp* cp38-* cp39-* cp310-* cp312-*"

          # gcc is required for gfortran
          CIBW_BEFORE_ALL_MACOS: >
            brew install boost eigen libomp gcc

      - name: Build wheels (macOS arm64)
        uses: pypa/cibuildwheel@v2.16.2
        if: ${{ startsWith(matrix.os, 'macos-12') }}
        env:
          CIBW_SKIP: "pp* cp38-* cp39-* cp310-* cp312-*"

          CIBW_ARCHS: arm64

          CIBW_BEFORE_ALL_MACOS: >
            brew install boost eigen gcc &&
            brew fetch --force --bottle-tag=arm64_monterey libomp &&
            brew reinstall $(brew --cache --bottle-tag=arm64_monterey libomp)

          CIBW_ENVIRONMENT_MACOS: FC="$(brew --prefix gcc)/bin/gfortran"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
